### ISSUE TITLE
What is the direction of painting when selecting starting point X Y ?

### ISSUE THREAD

**Issue by OkayOkayOkayOkay** [sirPinwheel/XY_painter_for_twitch#2]
https://imgur.com/cPqmRLu

What direction does it paint?

**Comment by sirPinwheel** [comment]
the starting point X Y is the bottom left corner of the picture, bot starts from bottom left and draws in horizontal lines.

X is the horizontal axis (starts X pixels away from the left edge)
Y is the vertical axis (starts Y pixels away from the bottom)
