### ISSUE TITLE
Specific picture doesn't work

### ISSUE THREAD

**Issue by OkayOkayOkayOkay** [sirPinwheel/XY_painter_for_twitch#4]
For some reason a specific picture doesn't work.

drawing C:\Users\USER\Pictures\PixelArt\AngryMonkey.gif at 500 x 0 Traceback (most recent call last): File "D:\Python\XY_painter_for_twitch-master\XY_painter_for_twitch-master\main.py", line 81, in <module> if __name__ == "__main__": main() File "D:\Python\XY_painter_for_twitch-master\XY_painter_for_twitch-master\main.py", line 74, in main draw(sys.argv[1], start_x, start_y) File "D:\Python\XY_painter_for_twitch-master\XY_painter_for_twitch-master\main.py", line 20, in draw else: raise RuntimeError('Image type could not be identified') RuntimeError: Image type could not be identified

I tried other picture and it does work. So what is the problem with the picture above?

**Comment by sirPinwheel** [comment]
That's most likely because 'gif' format, as of now it's not supported if you want to draw it you should convert to a different format, 'png' works best. I'll see if i can add gif support

**Comment by OkayOkayOkayOkay** [comment]
I see. But why would people make a picture in 'gif' format? I've noticed something in the properties, for 'gif' formats it says the 'bit depth' is 8 while for 'png' format it is 32. What does it mean?

Anyway, is it possible to make 'gif' format to work if it's just a picture?
